### ISSUE TITLE
Create custom taglib org.zkoss.xel.XelException: Resource not found

### ISSUE THREAD

**Issue by sesong11** [zkoss/zkspringboot#15]
Project : zkspringboot-security-demo
on my zul file I add this 

`<?taglib uri="~./security.tld" prefix="sec"?>`

and add security.tld file in resources/web/ folder

when I open my zul file it throw exception

```
org.zkoss.xel.XelException: Resource not found: /~./security.tld
	at org.zkoss.xel.util.TaglibMapper.load(TaglibMapper.java:108) ~[zcommon-8.5.0.jar:8.5.0]
	at org.zkoss.xel.util.TaglibMapper.load(TaglibMapper.java:93) ~[zcommon-8.5.0.jar:8.5.0]
```

**Comment by cor3000** [comment]
I assume you are using the optional jar zkspring-security which provides this taglib:
```
<dependency>
	<groupId>org.zkoss.zk</groupId>
	<artifactId>zkspring-security</artifactId>
	<version>4.0.0</version>
</dependency>
```
Then the correct taglib declaration and usage is (Please let me know where you found this incorrect usage "~./security.tld"):
```
<?taglib uri="http://www.zkoss.org/zkspring/security" prefix="sec"?>
<zk>
    You have the role user: ${sec:isAnyGranted('ROLE_USER')}
</zk>
```

I already updated our zkspring-security documentation [documentation](https://www.zkoss.org/wiki/ZK_Developer%27s_Reference/Integration/Security/Spring_Security#Secure_Components).

The [latest example project](https://github.com/zkoss/zkspring/blob/master/zkspringessentials/zkspringcoresec/src/main/webapp/secure/index.zul#L2) already contains this as well (since March 2018)

Be sure to also add the dependency:

```
<dependency>
	<groupId>org.springframework.security</groupId>
	<artifactId>spring-security-acl</artifactId>
	<version>[YOUR SPRING SECURITY VERSION]</version>
</dependency>
```
