### ISSUE TITLE
Error zip END header not found

### ISSUE THREAD

**Issue by sesong11** [zkoss/zkspringboot#16]
Error when I update to version 2.3.0. I can't build my project.

.m2\repository\org\zkoss\zkspringboot\zkspringboot-starter\2.3.0\zkspringboot-starter-2.3.0.jar; zip END header not found

**Comment by cor3000** [comment]
Thanks for the info, the jar shouldn't be there at all, the starter is meant to be a POM only dependency.
Since you didn't specify the way you use the dependency in your project, I can't test your case, here the intended way we use it in our demos:

https://github.com/zkoss/zkspringboot/blob/master/zkspringboot-demos/zkspringboot-minimal-jar/pom.xml##L28-L32

Be sure to specify `<type>pom</type>`

**Comment by cor3000** [comment]
just released 2.3.1 which doesn't contain the invalid jar
2.3.0 has been corrected (deleted the obsolete/broken jar)
