### ISSUE TITLE
session timeout does not work with Spring Security

### ISSUE THREAD

**Issue by gushakov** [zkoss/zkspringboot#26]
Hello ZK team,

I have noticed that when an application is protected with Spring Security (as in the corresponding demo module here), setting a timeout (with a redirect or the default popup with a message) does not seem to work. I have detailed the issue in the following gist:

[https://gist.github.com/gushakov/f2063e279223828be50c26d070bace46](https://gist.github.com/gushakov/f2063e279223828be50c26d070bace46)

In short, ZK will fire a POST to `/zkau` when timeout occurs, and of course,  Spring Security blocks all POSTs to `/zkau` other than the ones specifically allowed in [WebSecurityConfig.java](https://github.com/zkoss/zkspringboot/blob/master/zkspringboot-demos/zkspringboot-security-demo/src/main/java/org/zkoss/zkspringboot/security/WebSecurityConfig.java).

As the workaround, we can add a `permitAll()` exception for POSTs with "dummy" `cmd_0` parameter, as shown in the gist above.

But this does not seem as a durable solution. There is also the problem with timeout if we set it with this

```java
WebApps.getCurrent().getConfiguration().setAutomaticTimeout("ajax", false);
```

In this case, the timeout redirect (popup) will only be triggered after the first POST request from the client explicitly sent by the client after the period of inactivity. In this case, we can't set the exception in the security configuration at all, since there is no way to distinguish such POSTs (after the timeout) from the normal POSTs to `/zkau`.

I hope this little analysis helps you to further investigate and correct the issue,

Thank you.

Best regards, 

George

**Comment by cor3000** [comment]
This is a known limitation happening outside the scope of ZK, as you noted spring-security is blocking the request if configured to do so - I assume you redirect to a login page for all requests.

The same effect applies to all kind of SSO authentication proxies which simply perform a redirect for any unauthorized request that can't handle redirects.
Instead spring security (or any authentication filter/proxy) can be configured to return with an error (e.g: 403 Forbidden) instead of a redirect (302).

```
		.and()
                    .exceptionHandling()
                    .defaultAuthenticationEntryPointFor(
                            new Http403ForbiddenEntryPoint(),
                            new AntPathRequestMatcher(ZKAU, "POST"))
```

https://gist.github.com/cor3000/1377ecfa92728b8f3c6954aaf1067e17

Response errors can be handled by configuration in zk.xml

```
    <client-config>
        <!-- not working in all versions - https://tracker.zkoss.org/browse/ZK-4742 -->
        <error-reload>
            <device-type>ajax</device-type>
            <error-code>403</error-code>
            <reload-uri>/login</reload-uri>
        </error-reload>
    </client-config>
```

However that doesn't mean that this idea is perfect to all situations, it's just a way to avoid redirects for AJAX requests to an html (login) page, which obviously makes no sense.

I also haven't tested this for a while so there might have been some API changes since spring 5.4.
