### ISSUE TITLE
Cannot resolve org.zkoss.zkspringboot:zkspringboot-starter:2.5.12 @ https://mavensync.zkoss.org/maven2

### ISSUE THREAD

**Issue by afreller-1wa** [zkoss/zkspringboot#29]
To fix spring 4 shell vulnerability in upgrading to 2.5.12 version of spring boot, I ran into the problem that the corresponding zkspringboot dependencies are not available at maven repository https://mavensync.zkoss.org/maven2. 

I only see 2.5.3. Please make 2.5.12 available under https://mavensync.zkoss.org/maven2

Thank you.

Details pom.xml snippet:
`		<dependency>
			<groupId>org.zkoss.zkspringboot</groupId>
			<artifactId>zkspringboot-starter</artifactId>
			<version>${zkspringboot.version}</version>
			<type>pom</type>
		</dependency>
`

**Comment by cor3000** [comment]
The -starter dependency had hard coded versions in it. In order to pick your own version you can always use the zkspringboot-autoconfig module (not just in case of vulnerability) and pick your preferred Sprung-Boot version. The starter is essentially just pre picked dependencies (to get you started easily) and not required to configure ok under spring boot.

**Comment by hawkchen** [comment]
zkspringboot-starter 2.5.12 released at https://mavensync.zkoss.org/maven2/org/zkoss/zkspringboot/zkspringboot-starter/2.5.12/

**Comment by afreller-1wa** [comment]
Thank you for updating the maven repo!
