### ISSUE TITLE
Design login page using ZK with MVVM?

### ISSUE THREAD

**Issue by davoutuk** [zkoss/zkspringboot#9]
Looking at your demo with Spring Security,  the login form is pretty basic.

Is it possible to have the login page designed using a ZUL file with MVVM controller?

I have a consistent ZK page design for my web app, and I'd like to use this for the login page - by placing the user id/password input controls inside a panel with the general ZK page

**Comment by cor3000** [comment]
The clear recommendation is not to implement security/login features yourself unless you're an expert. That's why we keep the example as basic as possible to emphasize we have no one-size-fits-all solution on how you should implement your security concerns. 

You clearly can use a ZK page and MVVM semantics to do so, but you'll have to allow more unauthorized requests to ZK's internal servlets. 

If your requirement is only about the layout, then I'd favor including ZK's stylesheets and building a static layout using those styles.
